footprint: [[0.70, 0.65], [0.70, -0.65], [-0.70, -0.65], [-0.75, 0.65]]
observation_sources: laser_scan_sensor
laser_scan_sensor:
  sensor_frame: front_laser #laser_link
  data_type: LaserScan
  topic: /front/scan #scan
  marking: true
  clearing: true
